version: "3"
services:
  api:
    build:
      context: flask
    image: server:flask
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./flask:/flask
      - /mnt/RD/AQUA/image:/flask/image
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    container_name: flask
  app:
    build:
      context: web
    volumes:
      - ./web:/web
      - /web/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    image: web:react
    container_name: react
    command: npm start